# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('http', ['core','internet', 'config-store','applications'])
    module.source = [
        'helper/http-helper.cc',
        'model/http-client.cc',
        'model/http-server.cc',
        'model/http-distribution.cc',
        'model/http-controller.cc',
        'model/http-random-variable.cc',
        ]

    module_test = bld.create_ns3_module_test_library('http')
    module_test.source = [
        'test/http-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'http'
    headers.source = [
        'helper/http-helper.h',
        'model/http-client.h',
        'model/http-server.h',
        'model/http-distribution.h',
        'model/http-controller.h',
        'model/http-random-variable.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

